/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_Hotel;
import Controlador.Controlador_Huesped;
import Controlador.Controlador_Habitaciones;
import Controlador.Controlador_Reservas;

import Modelo.*;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author natam
 */
public class frmPrincipal extends javax.swing.JFrame {

    Controlador_Hotel controladorHotel;
    Controlador_Huesped controladorHuesped;
    Controlador_Habitaciones controladorHabitacion;
    Controlador_Reservas controladorReserva;
    private boolean cargandoDatos = false;

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        llenarCombos();
        controladorHotel = new Controlador_Hotel();
        controladorHuesped = new Controlador_Huesped();
        controladorHabitacion = new Controlador_Habitaciones();
        controladorReserva = new Controlador_Reservas();
        controladorHotel = new Controlador_Hotel(new Hotel("Hotel CAPRI", "Colombia"), controladorHabitacion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHotel = new javax.swing.JLabel();
        tblRegistroClientes = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblDocumetoHuesped = new javax.swing.JLabel();
        txtDocumentoHuesped = new javax.swing.JTextField();
        lblNombreHuesped = new javax.swing.JLabel();
        txtNombreHuesped = new javax.swing.JTextField();
        lblCorreoHuesped = new javax.swing.JLabel();
        txtCorreoHuesped = new javax.swing.JTextField();
        lblTelefonoHuesped = new javax.swing.JLabel();
        txtTelefonoHuesped = new javax.swing.JTextField();
        lblApellidosHuesped = new javax.swing.JLabel();
        txtApellidosHuesped = new javax.swing.JTextField();
        btnRegistrarHuesped = new javax.swing.JButton();
        btnActualizarHuesped = new javax.swing.JButton();
        btnEliminarHuesped = new javax.swing.JButton();
        btnBuscarHuesped = new javax.swing.JButton();
        panel2 = new java.awt.Panel();
        lblNumeroDeHabitacion = new javax.swing.JLabel();
        txtNumeroDeHabitacion = new javax.swing.JTextField();
        lblPrecioPorNoche = new javax.swing.JLabel();
        txtPrecioPorNoche = new javax.swing.JTextField();
        lblTipoDeHabitacion = new javax.swing.JLabel();
        rdbHabitacionSimple = new javax.swing.JRadioButton();
        rdbHabitacionDoble = new javax.swing.JRadioButton();
        rdbHabitacionSuit = new javax.swing.JRadioButton();
        lblDisponible = new javax.swing.JLabel();
        cbxConsultarDisponible = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnDisponibilidad = new javax.swing.JButton();
        Reservas = new javax.swing.JPanel();
        lblNumeroPersonas = new javax.swing.JLabel();
        cbxNumeroPersonas = new javax.swing.JComboBox<>();
        btnCrearReserva = new javax.swing.JButton();
        lblNumeroDeHabitacionReserva = new javax.swing.JLabel();
        cbxNumeroDeHabitaciones = new javax.swing.JComboBox<>();
        lblFechaDeIngreso = new javax.swing.JLabel();
        cbxDiaIngreso = new javax.swing.JComboBox<>();
        lblDiaIngreso = new javax.swing.JLabel();
        cbxMesIngreso = new javax.swing.JComboBox<>();
        lblMesIngreso = new javax.swing.JLabel();
        lblFechaDeSalida = new javax.swing.JLabel();
        lblDiaSalida = new javax.swing.JLabel();
        lblMesSalida = new javax.swing.JLabel();
        cbxDiaSalida = new javax.swing.JComboBox<>();
        cbxMesSalida = new javax.swing.JComboBox<>();
        btnBuscarReserva = new javax.swing.JButton();
        btnCancelarReserva = new javax.swing.JButton();
        lblCostoTotal = new javax.swing.JLabel();
        btnCalcularCostoTotal = new javax.swing.JButton();
        btnGenerarComprobante = new javax.swing.JButton();
        btnCantidadReservas = new javax.swing.JButton();
        btnMostrarReservas = new javax.swing.JButton();
        lblDocumentoReserva = new javax.swing.JLabel();
        txtDocumentoReserva = new javax.swing.JTextField();
        lblAnioIngreso = new javax.swing.JLabel();
        cbxAnioIngreso = new javax.swing.JComboBox<>();
        lblAnioSalida = new javax.swing.JLabel();
        cbxAnioSalida = new javax.swing.JComboBox<>();
        panel1 = new java.awt.Panel();
        lblTotalHabitaciones = new javax.swing.JLabel();
        txtTotalHabitaciones = new javax.swing.JTextField();
        lblHabitacionesDisponibles = new javax.swing.JLabel();
        txtHabitacionesDisponibles = new javax.swing.JTextField();
        lblHabitacionesOcupadas = new javax.swing.JLabel();
        txtHabitacionesOcupadas = new javax.swing.JTextField();
        lblPorcentajeOcupacion = new javax.swing.JLabel();
        txtPorcentajeOcupacion = new javax.swing.JTextField();
        btnMostrarInformacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHotel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 36)); // NOI18N
        lblHotel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHotel.setText("HOTEL CAPRI");

        lblDocumetoHuesped.setText("Documento");

        txtDocumentoHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoHuespedActionPerformed(evt);
            }
        });

        lblNombreHuesped.setText("Nombre");

        lblCorreoHuesped.setText("Correo");

        txtCorreoHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoHuespedActionPerformed(evt);
            }
        });

        lblTelefonoHuesped.setText("Telefono");

        txtTelefonoHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoHuespedActionPerformed(evt);
            }
        });

        lblApellidosHuesped.setText("Apellidos");

        btnRegistrarHuesped.setText("Registrar");
        btnRegistrarHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarHuespedActionPerformed(evt);
            }
        });

        btnActualizarHuesped.setText("Actualizar");
        btnActualizarHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarHuespedActionPerformed(evt);
            }
        });

        btnEliminarHuesped.setText("Eliminar");
        btnEliminarHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarHuespedActionPerformed(evt);
            }
        });

        btnBuscarHuesped.setText("Buscar");
        btnBuscarHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarHuespedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombreHuesped)
                    .addComponent(lblDocumetoHuesped)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCorreoHuesped)
                        .addComponent(lblApellidosHuesped))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTelefonoHuesped)
                        .addGap(4, 4, 4)))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTelefonoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocumentoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidosHuesped, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addComponent(txtNombreHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreoHuesped))
                .addGap(107, 107, 107)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarHuesped)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnBuscarHuesped, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrarHuesped, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(368, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDocumentoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRegistrarHuesped))
                    .addComponent(lblDocumetoHuesped))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreHuesped)
                    .addComponent(txtNombreHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarHuesped))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellidosHuesped)
                            .addComponent(txtApellidosHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizarHuesped)
                        .addGap(4, 4, 4)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorreoHuesped))
                .addGap(5, 5, 5)
                .addComponent(btnEliminarHuesped)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefonoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefonoHuesped))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        tblRegistroClientes.addTab("Registro de huespedes", jPanel2);

        lblNumeroDeHabitacion.setText("Numero de habitacion");

        lblPrecioPorNoche.setText("Precio por noche");

        lblTipoDeHabitacion.setText("Tipo de habitacion");

        rdbHabitacionSimple.setText("Simple");

        rdbHabitacionDoble.setText("Doble");

        rdbHabitacionSuit.setText("Suite");

        lblDisponible.setText("Disponible");

        cbxConsultarDisponible.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        cbxConsultarDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxConsultarDisponibleActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnDisponibilidad.setText("Consultar disponibilidad");
        btnDisponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisponibilidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNumeroDeHabitacion)
                            .addComponent(lblDisponible))
                        .addGap(18, 18, 18)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel2Layout.createSequentialGroup()
                                .addComponent(cbxConsultarDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103))
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(txtNumeroDeHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88))))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(btnDisponibilidad)
                        .addGap(18, 18, 18)))
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTipoDeHabitacion)
                    .addComponent(lblPrecioPorNoche))
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(txtPrecioPorNoche, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar)
                            .addComponent(btnRegistrar)
                            .addComponent(btnActualizar)
                            .addComponent(btnEliminar))
                        .addGap(78, 78, 78))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(rdbHabitacionSimple)
                        .addGap(18, 18, 18)
                        .addComponent(rdbHabitacionDoble)
                        .addGap(27, 27, 27)
                        .addComponent(rdbHabitacionSuit)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btnRegistrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumeroDeHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumeroDeHabitacion)
                            .addComponent(lblTipoDeHabitacion)
                            .addComponent(rdbHabitacionSimple)
                            .addComponent(rdbHabitacionDoble)
                            .addComponent(rdbHabitacionSuit))
                        .addGap(26, 26, 26)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecioPorNoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecioPorNoche))
                        .addGap(14, 14, 14)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDisponible)
                            .addComponent(cbxConsultarDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(7, 7, 7)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(btnActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnDisponibilidad)))
                .addContainerGap(199, Short.MAX_VALUE))
        );

        tblRegistroClientes.addTab("Habitaciones", panel2);

        lblNumeroPersonas.setText("Numero de personas");

        cbxNumeroPersonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        btnCrearReserva.setText("Crear");
        btnCrearReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearReservaActionPerformed(evt);
            }
        });

        lblNumeroDeHabitacionReserva.setText("Numero de habitacion");

        cbxNumeroDeHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNumeroDeHabitacionesActionPerformed(evt);
            }
        });

        lblFechaDeIngreso.setText("Fecha de ingreso");

        cbxDiaIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDiaIngresoActionPerformed(evt);
            }
        });

        lblDiaIngreso.setText("Dia");

        lblMesIngreso.setText("Mes");

        lblFechaDeSalida.setText("Fecha de salida");

        lblDiaSalida.setText("Dia");

        lblMesSalida.setText("Mes");

        btnBuscarReserva.setText("Buscar");
        btnBuscarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarReservaActionPerformed(evt);
            }
        });

        btnCancelarReserva.setText("Cancelar");
        btnCancelarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarReservaActionPerformed(evt);
            }
        });

        lblCostoTotal.setText("Costo total");

        btnCalcularCostoTotal.setText("Calcular costo");
        btnCalcularCostoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularCostoTotalActionPerformed(evt);
            }
        });

        btnGenerarComprobante.setText("Generar comprobante");
        btnGenerarComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarComprobanteActionPerformed(evt);
            }
        });

        btnCantidadReservas.setText("Cantidad de reserrvas");
        btnCantidadReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantidadReservasActionPerformed(evt);
            }
        });

        btnMostrarReservas.setText("Mostrar reservas");
        btnMostrarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarReservasActionPerformed(evt);
            }
        });

        lblDocumentoReserva.setText("Documento ");

        lblAnioIngreso.setText("Año");

        lblAnioSalida.setText("Año");

        javax.swing.GroupLayout ReservasLayout = new javax.swing.GroupLayout(Reservas);
        Reservas.setLayout(ReservasLayout);
        ReservasLayout.setHorizontalGroup(
            ReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReservasLayout.createSequentialGroup()
                .addContainerGap(685, Short.MAX_VALUE)
                .addGroup(ReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReservasLayout.createSequentialGroup()
                        .addComponent(btnCrearReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(btnBuscarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReservasLayout.createSequentialGroup()
                        .addGroup(ReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCantidadReservas)
                            .addComponent(btnMostrarReservas))
                        .addGap(51, 51, 51))))
            .addGroup(ReservasLayout.createSequentialGroup()
                .addGroup(ReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReservasLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(ReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ReservasLayout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(lblDiaIngreso)
                                .addGap(123, 123, 123)
                                .addComponent(lblAnioIngreso)
                                .addGap(105, 105, 105)
                                .addComponent(lblFechaDeSalida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxDiaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxMesSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxAnioSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ReservasLayout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(lblMesIngreso)
                                .addGap(306, 306, 306)
                                .addComponent(lblDiaSalida)
                                .addGap(62, 62, 62)
                                .addComponent(lblMesSalida)
                                .addGap(52, 52, 52)
                                .addComponent(lblAnioSalida))
                            .addGroup(ReservasLayout.createSequentialGroup()
                                .addComponent(lblNumeroDeHabitacionReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxNumeroDeHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ReservasLayout.createSequentialGroup()
                                .addGroup(ReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(ReservasLayout.createSequentialGroup()
                                        .addComponent(lblDocumentoReserva)
                                        .addGap(41, 41, 41)
                                        .addComponent(txtDocumentoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ReservasLayout.createSequentialGroup()
                                        .addGap(266, 266, 266)
                                        .addComponent(lblNumeroPersonas)))
                                .addGap(18, 18, 18)
                                .addComponent(cbxNumeroPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ReservasLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnGenerarComprobante))
                    .addGroup(ReservasLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(ReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ReservasLayout.createSequentialGroup()
                                .addComponent(lblCostoTotal)
                                .addGap(18, 18, 18)
                                .addComponent(btnCalcularCostoTotal))
                            .addGroup(ReservasLayout.createSequentialGroup()
                                .addComponent(lblFechaDeIngreso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxDiaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxMesIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxAnioIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(339, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReservasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelarReserva)
                .addGap(260, 260, 260))
        );
        ReservasLayout.setVerticalGroup(
            ReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReservasLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(ReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReservasLayout.createSequentialGroup()
                        .addGroup(ReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDocumentoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDocumentoReserva)
                            .addComponent(btnCrearReserva))
                        .addGap(49, 49, 49)
                        .addGroup(ReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumeroDeHabitacionReserva)
                            .addComponent(cbxNumeroDeHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumeroPersonas)
                            .addComponent(cbxNumeroPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ReservasLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(ReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDiaSalida)
                                    .addComponent(lblMesSalida)
                                    .addComponent(lblAnioSalida))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxDiaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFechaDeSalida)
                                    .addComponent(cbxMesSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxAnioSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                .addComponent(btnCantidadReservas)
                                .addGap(18, 18, 18)
                                .addGroup(ReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnMostrarReservas)
                                    .addComponent(btnGenerarComprobante))
                                .addGap(67, 67, 67))
                            .addGroup(ReservasLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(ReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDiaIngreso)
                                    .addComponent(lblMesIngreso)
                                    .addComponent(lblAnioIngreso))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFechaDeIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxDiaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxMesIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxAnioIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(ReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCostoTotal)
                                    .addComponent(btnCalcularCostoTotal))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(ReservasLayout.createSequentialGroup()
                        .addComponent(btnBuscarReserva)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarReserva)
                        .addContainerGap())))
        );

        tblRegistroClientes.addTab("Reservas", Reservas);

        lblTotalHabitaciones.setText("Total habitaciones");

        lblHabitacionesDisponibles.setText("Disponibles");

        lblHabitacionesOcupadas.setText("Ocupadas");

        lblPorcentajeOcupacion.setText("% ocupacion");

        txtPorcentajeOcupacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPorcentajeOcupacionActionPerformed(evt);
            }
        });

        btnMostrarInformacion.setText("Mostrar informacion");
        btnMostrarInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarInformacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel1Layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(lblTotalHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel1Layout.createSequentialGroup()
                                .addComponent(lblHabitacionesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHabitacionesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lblHabitacionesOcupadas, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHabitacionesOcupadas))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel1Layout.createSequentialGroup()
                                .addComponent(lblPorcentajeOcupacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPorcentajeOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 374, Short.MAX_VALUE)
                        .addComponent(btnMostrarInformacion)
                        .addGap(287, 287, 287))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalHabitaciones)
                    .addComponent(txtTotalHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHabitacionesDisponibles)
                    .addComponent(txtHabitacionesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHabitacionesOcupadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHabitacionesOcupadas)
                    .addComponent(btnMostrarInformacion))
                .addGap(31, 31, 31)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPorcentajeOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPorcentajeOcupacion))
                .addContainerGap(207, Short.MAX_VALUE))
        );

        tblRegistroClientes.addTab("Gestion hotelera", panel1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblRegistroClientes)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addComponent(lblHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(tblRegistroClientes))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDocumentoHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoHuespedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoHuespedActionPerformed

    private void txtCorreoHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoHuespedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoHuespedActionPerformed

    private void txtTelefonoHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoHuespedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoHuespedActionPerformed

    private void btnRegistrarHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarHuespedActionPerformed
        // TODO add your handling code here:
        registrarHuesped();
    }//GEN-LAST:event_btnRegistrarHuespedActionPerformed

    private void btnEliminarHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarHuespedActionPerformed
        // TODO add your handling code here:
        eliminarHuesped();
    }//GEN-LAST:event_btnEliminarHuespedActionPerformed

    private void btnBuscarHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHuespedActionPerformed
        // TODO add your handling code here:
        buscarHuesped();
    }//GEN-LAST:event_btnBuscarHuespedActionPerformed

    private void btnCrearReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearReservaActionPerformed
        // TODO add your handling code here:
        crearReserva();
    }//GEN-LAST:event_btnCrearReservaActionPerformed

    private void cbxNumeroDeHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNumeroDeHabitacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNumeroDeHabitacionesActionPerformed

    private void cbxDiaIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDiaIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDiaIngresoActionPerformed

    private void btnBuscarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarReservaActionPerformed
        // TODO add your handling code here:
        buscarReserva();
    }//GEN-LAST:event_btnBuscarReservaActionPerformed

    private void btnCancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarReservaActionPerformed
        // TODO add your handling code here:
        cancelarReserva();
    }//GEN-LAST:event_btnCancelarReservaActionPerformed

    private void txtPorcentajeOcupacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPorcentajeOcupacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPorcentajeOcupacionActionPerformed

    private void btnActualizarHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarHuespedActionPerformed
        // TODO add your handling code here:
        actualizarHuesped();
    }//GEN-LAST:event_btnActualizarHuespedActionPerformed

    private void btnCalcularCostoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularCostoTotalActionPerformed
        // TODO add your handling code here:
        calcularCostoTotal();
    }//GEN-LAST:event_btnCalcularCostoTotalActionPerformed

    private void btnGenerarComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarComprobanteActionPerformed
        // TODO add your handling code here:
        generarComprobante();
    }//GEN-LAST:event_btnGenerarComprobanteActionPerformed

    private void btnCantidadReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantidadReservasActionPerformed
        // TODO add your handling code here:
        cantidadReservas();
    }//GEN-LAST:event_btnCantidadReservasActionPerformed

    private void btnMostrarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarReservasActionPerformed
        // TODO add your handling code here:
        mostrarReservas();
    }//GEN-LAST:event_btnMostrarReservasActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        registrarHabitacion();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        buscarHabitacion();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        actualizarHabitacion();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        eliminarHabitacion();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnDisponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisponibilidadActionPerformed
        // TODO add your handling code here:
        consultarDisponibilidad();
    }//GEN-LAST:event_btnDisponibilidadActionPerformed

    private void cbxConsultarDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxConsultarDisponibleActionPerformed
        // TODO add your handling code here:
        if (cargandoDatos) {
            return;
        }
    }//GEN-LAST:event_cbxConsultarDisponibleActionPerformed

    private void btnMostrarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarInformacionActionPerformed
        // TODO add your handling code here:
        mostrarInformacionHotelera();
    }//GEN-LAST:event_btnMostrarInformacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Reservas;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizarHuesped;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarHuesped;
    private javax.swing.JButton btnBuscarReserva;
    private javax.swing.JButton btnCalcularCostoTotal;
    private javax.swing.JButton btnCancelarReserva;
    private javax.swing.JButton btnCantidadReservas;
    private javax.swing.JButton btnCrearReserva;
    private javax.swing.JButton btnDisponibilidad;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarHuesped;
    private javax.swing.JButton btnGenerarComprobante;
    private javax.swing.JButton btnMostrarInformacion;
    private javax.swing.JButton btnMostrarReservas;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrarHuesped;
    private javax.swing.JComboBox<String> cbxAnioIngreso;
    private javax.swing.JComboBox<String> cbxAnioSalida;
    private javax.swing.JComboBox<String> cbxConsultarDisponible;
    private javax.swing.JComboBox<String> cbxDiaIngreso;
    private javax.swing.JComboBox<String> cbxDiaSalida;
    private javax.swing.JComboBox<String> cbxMesIngreso;
    private javax.swing.JComboBox<String> cbxMesSalida;
    private javax.swing.JComboBox<String> cbxNumeroDeHabitaciones;
    private javax.swing.JComboBox<String> cbxNumeroPersonas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAnioIngreso;
    private javax.swing.JLabel lblAnioSalida;
    private javax.swing.JLabel lblApellidosHuesped;
    private javax.swing.JLabel lblCorreoHuesped;
    private javax.swing.JLabel lblCostoTotal;
    private javax.swing.JLabel lblDiaIngreso;
    private javax.swing.JLabel lblDiaSalida;
    private javax.swing.JLabel lblDisponible;
    private javax.swing.JLabel lblDocumentoReserva;
    private javax.swing.JLabel lblDocumetoHuesped;
    private javax.swing.JLabel lblFechaDeIngreso;
    private javax.swing.JLabel lblFechaDeSalida;
    private javax.swing.JLabel lblHabitacionesDisponibles;
    private javax.swing.JLabel lblHabitacionesOcupadas;
    private javax.swing.JLabel lblHotel;
    private javax.swing.JLabel lblMesIngreso;
    private javax.swing.JLabel lblMesSalida;
    private javax.swing.JLabel lblNombreHuesped;
    private javax.swing.JLabel lblNumeroDeHabitacion;
    private javax.swing.JLabel lblNumeroDeHabitacionReserva;
    private javax.swing.JLabel lblNumeroPersonas;
    private javax.swing.JLabel lblPorcentajeOcupacion;
    private javax.swing.JLabel lblPrecioPorNoche;
    private javax.swing.JLabel lblTelefonoHuesped;
    private javax.swing.JLabel lblTipoDeHabitacion;
    private javax.swing.JLabel lblTotalHabitaciones;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JRadioButton rdbHabitacionDoble;
    private javax.swing.JRadioButton rdbHabitacionSimple;
    private javax.swing.JRadioButton rdbHabitacionSuit;
    private javax.swing.JTabbedPane tblRegistroClientes;
    private javax.swing.JTextField txtApellidosHuesped;
    private javax.swing.JTextField txtCorreoHuesped;
    private javax.swing.JTextField txtDocumentoHuesped;
    private javax.swing.JTextField txtDocumentoReserva;
    private javax.swing.JTextField txtHabitacionesDisponibles;
    private javax.swing.JTextField txtHabitacionesOcupadas;
    private javax.swing.JTextField txtNombreHuesped;
    private javax.swing.JTextField txtNumeroDeHabitacion;
    private javax.swing.JTextField txtPorcentajeOcupacion;
    private javax.swing.JTextField txtPrecioPorNoche;
    private javax.swing.JTextField txtTelefonoHuesped;
    private javax.swing.JTextField txtTotalHabitaciones;
    // End of variables declaration//GEN-END:variables

    private void llenarCombos() {
        // Día de ingreso
        for (int i = 31; i >= 1; i--) {
            cbxDiaIngreso.addItem(i + "");
        }
        // Mes de ingreso
        for (int i = 12; i >= 1; i--) {
            cbxMesIngreso.addItem(i + "");
        }
        // Año de nacimiento
        for (int i = LocalDate.now().getYear(); i >= 2026; i--) {
            cbxAnioIngreso.addItem(i + "");
        }
        //Dí salida
        for (int i = 31; i >= 1; i--) {
            cbxDiaSalida.addItem(i + "");
        }
        // Mes de ingreso
        for (int i = 12; i >= 1; i--) {
            cbxMesSalida.addItem(i + "");
        }
        // Año de nacimiento
        for (int i = LocalDate.now().getYear(); i >= 2026; i--) {
            cbxAnioSalida.addItem(i + "");
        }
    }

    private void cargarHabitacionesEnCombo() {

        cbxNumeroDeHabitaciones.removeAllItems();

        for (Habitacion h : controladorHabitacion.obtenerHabitaciones()) {

            cbxNumeroDeHabitaciones.addItem(String.valueOf(h.getNumero()));
        }
    }

    private void registrarHuesped() {

        String documento = txtDocumentoHuesped.getText();
        String nombre = txtNombreHuesped.getText();
        String apellido = txtApellidosHuesped.getText();
        String correo = txtCorreoHuesped.getText();
        String telefono = txtTelefonoHuesped.getText();

        if (documento.isEmpty()
                || nombre.isEmpty()
                || apellido.isEmpty()
                || correo.isEmpty()
                || telefono.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos");

            return;
        }
        

        Huesped nuevoHuesped = new Huesped(telefono, correo, nombre, apellido, documento);
        boolean registrado = controladorHuesped.registrarHuesped(nuevoHuesped);

        if (registrado) {
            JOptionPane.showMessageDialog(this, "Huésped registrado correctamente");
            System.out.println(nuevoHuesped.getNombre() + " - " + nuevoHuesped.getDocumento());
            limpiarCamposHuesped();

        } else {
            JOptionPane.showMessageDialog(this, "Ya existe un huésped con ese documento");
        }
    }

    private void buscarHuesped() {

        String documento = txtDocumentoHuesped.getText();

        if (documento.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el documento");
            return;
        }

        Huesped h = controladorHuesped.buscarHuesped(documento);

        if (h != null) {

            txtNombreHuesped.setText(h.getNombre());
            txtApellidosHuesped.setText(h.getApellido());
            txtCorreoHuesped.setText(h.getCorreo());
            txtTelefonoHuesped.setText(h.getNumero_telefono());
        } else {
            JOptionPane.showMessageDialog(this, "Huésped no encontrado");
        }
    }

    private void actualizarHuesped() {

        String documento = txtDocumentoHuesped.getText();
        String nombre = txtNombreHuesped.getText();
        String apellido = txtApellidosHuesped.getText();
        String correo = txtCorreoHuesped.getText();
        String telefono = txtTelefonoHuesped.getText();

        boolean actualizado = controladorHuesped.actualizarHuesped(documento, nombre, apellido, telefono, correo);

        if (actualizado) {
            JOptionPane.showMessageDialog(this, "Huésped actualizado correctamente");

        } else {
            JOptionPane.showMessageDialog(this, "No existe un huésped con ese documento");
        }
    }

    private void eliminarHuesped() {

        String documento = txtDocumentoHuesped.getText();

        if (documento.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el documento");
            return;
        }
        boolean eliminado = controladorHuesped.eliminarHuesped(documento);

        if (eliminado) {
            JOptionPane.showMessageDialog(this, "Huésped eliminado correctamente");
            limpiarCamposHuesped();

        } else {
            JOptionPane.showMessageDialog(this, "No existe un huésped con ese documento");
        }
    }

    private void limpiarCamposHuesped() {

        txtDocumentoHuesped.setText("");
        txtNombreHuesped.setText("");
        txtApellidosHuesped.setText("");
        txtCorreoHuesped.setText("");
        txtTelefonoHuesped.setText("");
    }

    private void registrarHabitacion() {

        int numero = Integer.parseInt(txtNumeroDeHabitacion.getText());
        double precio = Double.parseDouble(txtPrecioPorNoche.getText());
        String tipo = "";

        if (rdbHabitacionSimple.isSelected()) {

            tipo = "simple";
        } else if (rdbHabitacionDoble.isSelected()) {

            tipo = "doble";
        } else if (rdbHabitacionSuit.isSelected()) {

            tipo = "suite";
        }

        boolean disponible = cbxConsultarDisponible.getSelectedItem().toString().equalsIgnoreCase("Si");

        boolean registrada = controladorHabitacion.registrarHabitacion(numero, precio, tipo, disponible);

        if (registrada) {

            JOptionPane.showMessageDialog(this, "Habitación registrada correctamente");
            // Agregar automáticamente al combo de reservas
            cbxNumeroDeHabitaciones.addItem(String.valueOf(numero));
            cargarHabitacionesEnCombo();
            limpiarCamposHabitacion();

        } else {

            JOptionPane.showMessageDialog(this, "No fue posible registrar la habitación");
        }
    }

    private void buscarHabitacion() {

        String texto = txtNumeroDeHabitacion.getText();

        if (texto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese el número de habitación");
            return;
        }
        int numero = Integer.parseInt(txtNumeroDeHabitacion.getText());
        Habitacion habitacion = controladorHabitacion.consultarHabitacion(numero);

        if (habitacion == null) {
            JOptionPane.showMessageDialog(this, "Habitación no encontrada");
            return;
        }
        txtPrecioPorNoche.setText(String.valueOf(habitacion.getPrecioPorNoche()));

        if (habitacion.getTipo().equalsIgnoreCase("simple")) {
            rdbHabitacionSimple.setSelected(true);

        } else if (habitacion.getTipo().equalsIgnoreCase("doble")) {
            rdbHabitacionDoble.setSelected(true);

        } else {
            rdbHabitacionSuit.setSelected(true);
        }
        cargandoDatos = true;
        cbxConsultarDisponible.setSelectedItem(habitacion.isDisponible() ? "Si" : "No");
        cargandoDatos = false;

    }

    private void actualizarHabitacion() {

        int numero = Integer.parseInt(txtNumeroDeHabitacion.getText());
        double precio = Double.parseDouble(txtPrecioPorNoche.getText());
        boolean disponible = cbxConsultarDisponible.getSelectedItem().toString().equalsIgnoreCase("Si");
        boolean actualizada = controladorHabitacion.actualizarHabitacion(numero, precio, disponible);

        if (actualizada) {
            JOptionPane.showMessageDialog(this, "Habitación actualizada correctamente");

        } else {
            JOptionPane.showMessageDialog(this, "No fue posible actualizar la habitación");
        }
    }

    private void eliminarHabitacion() {

        int numero = Integer.parseInt(txtNumeroDeHabitacion.getText());
        boolean eliminada = controladorHabitacion.eliminarHabitacion(numero);

        if (eliminada) {
            JOptionPane.showMessageDialog(this, "Habitación eliminada correctamente");
            cargarHabitacionesEnCombo();
            limpiarCamposHabitacion();

        } else {
            JOptionPane.showMessageDialog(this, "No existe la habitación");
        }
    }

    private void consultarDisponibilidad() {
        String texto = txtNumeroDeHabitacion.getText().trim();

        if (texto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese el número de habitación");
            return;
        }

        int numero = Integer.parseInt(texto);
        Habitacion habitacion = controladorHabitacion.consultarHabitacion(numero);

        if (habitacion == null) {
            JOptionPane.showMessageDialog(this, "Habitación no encontrada");
            return;
        }

        String mensaje = habitacion.isDisponible() ? "La habitación está disponible" : "La habitación está ocupada";
        JOptionPane.showMessageDialog(this, mensaje);
    }

    private void limpiarCamposHabitacion() {

        txtNumeroDeHabitacion.setText("");
        txtPrecioPorNoche.setText("");

        rdbHabitacionSimple.setSelected(false);
        rdbHabitacionDoble.setSelected(false);
        rdbHabitacionSuit.setSelected(false);
        cbxConsultarDisponible.setSelectedIndex(0);
    }

    private void crearReserva() {

        String documento = txtDocumentoReserva.getText();

        if (documento.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el documento del huésped");
            return;
        }
        // Buscar huésped
        Huesped huespedEncontrado = controladorHuesped.buscarHuesped(documento);

        if (huespedEncontrado == null) {
            JOptionPane.showMessageDialog(this, "No existe un huésped con ese documento");
            return;
        }
        // Obtener habitación seleccionada
        int numeroHabitacion = Integer.parseInt(cbxNumeroDeHabitaciones.getSelectedItem().toString());
        Habitacion habitacionEncontrada = controladorHabitacion.consultarHabitacion(numeroHabitacion);

        if (habitacionEncontrada == null) {
            JOptionPane.showMessageDialog(this, "La habitación no existe");
            return;
        }
        // Fechas
        int diaIngreso = Integer.parseInt(cbxDiaIngreso.getSelectedItem().toString());
        int mesIngreso = Integer.parseInt(cbxMesIngreso.getSelectedItem().toString());
        int anioIngreso = Integer.parseInt(cbxAnioIngreso.getSelectedItem().toString());

        int diaSalida = Integer.parseInt(cbxDiaSalida.getSelectedItem().toString());
        int mesSalida = Integer.parseInt(cbxMesSalida.getSelectedItem().toString());
        int anioSalida = Integer.parseInt(cbxAnioSalida.getSelectedItem().toString());

        LocalDate fechaIngreso = LocalDate.of(anioIngreso, mesIngreso, diaIngreso);
        LocalDate fechaSalida = LocalDate.of(anioSalida, mesSalida, diaSalida);
        boolean creada = controladorReserva.crearReserva(huespedEncontrado, habitacionEncontrada, fechaIngreso, fechaSalida);

        if (creada) {
            JOptionPane.showMessageDialog(this, "Reserva creada correctamente");
            limpiarCamposReserva();

        } else {
            JOptionPane.showMessageDialog(this, "No fue posible crear la reserva");
        }
    }

    private void buscarReserva() {

        int numeroHabitacion = Integer.parseInt(cbxNumeroDeHabitaciones.getSelectedItem().toString());
        Reservas reserva = controladorReserva.buscarReserva(numeroHabitacion);

        if (reserva == null) {

            JOptionPane.showMessageDialog(this, "No existe una reserva para esa habitación");
            return;
        }

        txtDocumentoReserva.setText(reserva.getHuesped().getDocumento());
        JOptionPane.showMessageDialog(this, "Reserva encontrada");
    }

    private void cancelarReserva() {

        int numeroHabitacion = Integer.parseInt(cbxNumeroDeHabitaciones.getSelectedItem().toString());
        boolean cancelada = controladorReserva.cancelarReserva(numeroHabitacion);

        if (cancelada) {
            JOptionPane.showMessageDialog(this, "Reserva cancelada correctamente");

        } else {
            JOptionPane.showMessageDialog(this, "No existe una reserva activa para esa habitación");
        }
    }

    private void limpiarCamposReserva() {

        txtDocumentoReserva.setText("");
        cbxNumeroDeHabitaciones.setSelectedIndex(0);
        cbxNumeroPersonas.setSelectedIndex(0);
        cbxDiaIngreso.setSelectedIndex(0);
        cbxMesIngreso.setSelectedIndex(0);
        cbxAnioIngreso.setSelectedIndex(0);
        cbxDiaSalida.setSelectedIndex(0);
        cbxMesSalida.setSelectedIndex(0);
        cbxAnioSalida.setSelectedIndex(0);
    }

    private void calcularCostoTotal() {

        int numeroHabitacion = Integer.parseInt(cbxNumeroDeHabitaciones.getSelectedItem().toString().trim());
        double costo = controladorReserva.calcularCostoTotal(numeroHabitacion);

        if (costo <= 0) {
            JOptionPane.showMessageDialog(this, "No se pudo calcular el costo de la reserva");
            return;
        }
        JOptionPane.showMessageDialog(this, "Costo total de la reserva: $" + costo);
    }

    private void generarComprobante() {

        int numeroHabitacion = Integer.parseInt(cbxNumeroDeHabitaciones.getSelectedItem().toString());
        String comprobante = controladorReserva.generarComprobante(numeroHabitacion);
        JOptionPane.showMessageDialog(this, comprobante);
    }

    private void cantidadReservas() {

        int cantidad = controladorReserva.cantidadReservas();
        JOptionPane.showMessageDialog(this, "Cantidad de reservas: " + cantidad);
    }

    private void mostrarReservas() {

        ArrayList<Reservas> reservas = controladorReserva.obtenerReservas();

        if (reservas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay reservas registradas");
            return;
        }
        String mensaje = "";

        for (Reservas r : reservas) {

            mensaje
                    += "Huésped: "
                    + r.getHuesped().getNombre()
                    + "\nDocumento: "
                    + r.getHuesped().getDocumento()
                    + "\nHabitación: "
                    + r.getHabitacion().getNumero()
                    + "\nIngreso: "
                    + r.getFechaIngreso()
                    + "\nSalida: "
                    + r.getFechaSalida()
                    + "\nEstado: "
                    + r.getEstado()
                    + "\n---------------------------\n";
        }
        JOptionPane.showMessageDialog(this, mensaje);
    }

    private void mostrarInformacionHotelera() {

        txtTotalHabitaciones.setText(String.valueOf(controladorHotel.totalHabitaciones()));
        txtHabitacionesDisponibles.setText(String.valueOf(controladorHotel.habitacionesDisponibles()));
        txtHabitacionesOcupadas.setText(String.valueOf(controladorHotel.habitacionesOcupadas()));
        txtPorcentajeOcupacion.setText(String.format("%.1f%%", controladorHotel.porcentajeOcupacion()));
    }

}
